<?php
    include("../includes/navbar.php");
    include("../includes/data_base.php");
    $titulo_html="Categorias";
    include("../includes/header.php");
?>
<?php
    include("../includes/header.php");
?>